spring:
  profiles:
    active: local
  messages:
    basename: messages, errors
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC
    username: root
    password: 1234

mybatis:
  mapper-locations: classpath*:/mappers/mysql/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
  type-aliases-package: hello.board.domain

logging.level:
  org.springframework.jdbc:
    debug

server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800
  error:
    path: /error
